// ui/mainMenu.keyboard.ts
import { InlineKeyboard } from 'grammy'

export const mainMenuKeyboard = new InlineKeyboard()
  .text('Buy', 'cmd:buysol')
  .text('Fund', 'cmd:fund')
  .row()
  .text('✅ W1 (Master)', 'cmd:selectedwallet')
  .text('Change Wallet', 'cmd:changewallet')
  .row()
  .text('Help', 'cmd:help')
  .text('Refer Friends', 'cmd:refer')
  .text('Alerts', 'cmd:alerts')
  .row()
  .text('Wallet', 'cmd:wallet')
  .text('Settings', 'cmd:settings')
  .row()
  .text('DCA Orders', 'cmd:dcaorders')
  .text('Limit Orders', 'cmd:limitorders')
  .row()
  .text('Open Telemetry 📊', 'cmd:opentel')
  .text('Refresh', 'cmd:refresh')
