import { InlineKeyboard } from 'grammy'

export const walletMenu = new InlineKeyboard()
  .text('View on Solscan', 'cmd:txs')
  .text('Close', 'close')
  .row()
  .text('Deposit SOL', 'cmd:deposit')
  .text('Buy SOL', 'cmd:buysol')
  .row()
  .text('Withdraw all SOL', 'cmd:withdraw')
  .text('Withdraw X SOL', 'cmd:withdraw')
  .row()
  .text('Manage Wallets', 'cmd:managewallets')
  .text('Manage Tokens', 'cmd:managetkn')
  .row()
  .text('Reset All Wallets', 'cmd:wallet')
  .text('Export Seed Phrase', 'cmd:wallet')
  .row()
  .text('Refresh', 'cmd:wallet')
