import { InlineKeyboard } from 'grammy'

export const walletMenu = new InlineKeyboard()
  .text('View on Solscan', 'cmd:txs')
  .text('Close', 'cmd:wallet')
  .row()
  .text('Deposit SOL', 'cmd:deposit')
  .text('Buy SOL', 'cmd:buysol')
  .row()
  .text('Withdraw all SOL', 'cmd:settings')
  .text('Withdraw X SOL', 'cmd:help')
  .row()
  .text('Manage Wallets', 'cmd:wallet')
  .text('Manage Tokens', 'cmd:wallet')
  .row()
  .text('Reset All Wallets', 'cmd:wallet')
  .text('Export Seed Phrase', 'cmd:wallet')
  .row()
  .text('Refresh', 'cmd:wallet')
